### ISSUE TITLE
Build fails for blog posts with multiple authors

### ISSUE THREAD

**Issue by shochdoerfer** [stackql/docusaurus-plugin-structured-data#1]
First of all, thanks for the awesome plugin!

We installed the plugin for a while now, but a few days ago, our builds started failing. The respective blog post that fails the build contains a [list of authors](https://docusaurus.io/docs/blog#blog-post-authors) defined like this:
```
---
authors: [user1, user2]
---
```

When running `yarn build` the build fails with the following error:
```
[ERROR] TypeError: Cannot read properties of undefined (reading 'authorId')
    at ./node_modules/@stackql/docusaurus-plugin-structured-data/src/index.js:346:112
```

**Comment by jeffreyaven** [comment]
hey @shochdoerfer, fixed (or worked around) https://github.com/stackql/docusaurus-plugin-structured-data/commit/ac1ba9cd957b2aea67600f83ef45ba6a3fb661ef

**Comment by shochdoerfer** [comment]
wow, that was a quick fix ;) Will test later. Thanks a lot!

**Comment by jeffreyaven** [comment]
Thanks! Quick favour can you ⭐ our main repo https://github.com/stackql/stackql
